In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('Fish_dataset.csv')

In [4]:
import warning
warning.filterwarning("ignore")

ModuleNotFoundError: No module named 'warning'

In [5]:
data

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [6]:
data['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [7]:
data.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [8]:
colname=[]
for x in data.columns:
    if data[x].dtypes=='object':
        colname.append(x)
colname        


['Species']

In [9]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

for x in colname:
    data[x]=le.fit_transform(data[x])
    
    
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)

Feature Species
mapping {'Bream': 0, 'Parkki': 1, 'Perch': 2, 'Pike': 3, 'Roach': 4, 'Smelt': 5, 'Whitefish': 6}


In [10]:
X = data[['Weight', 'Length1', 'Length2', 'Length3', 'Height', 'Width'] ]
Y = data['Species']

In [11]:
X.shape

(159, 6)

In [12]:
Y.shape

(159,)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(X)
X = scaler.transform(X)

In [14]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [15]:
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=int(np.sqrt(len(X_train))),
                              metric='euclidean')

In [16]:
model_KNN.fit(X_train,Y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=11)

In [17]:
Y_pred=model_KNN.predict(X_test)
print(list(zip(Y_test,Y_pred)))

[(4, 2), (2, 2), (4, 2), (0, 0), (3, 2), (2, 2), (3, 2), (0, 0), (6, 2), (2, 2), (1, 1), (1, 2), (4, 2), (0, 0), (4, 2), (5, 5), (2, 2), (0, 0), (1, 4), (2, 4), (0, 0), (2, 2), (5, 5), (2, 2), (0, 0), (4, 2), (2, 2), (6, 2), (3, 3), (5, 5), (2, 2), (1, 4)]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[6 0 0 0 0 0 0]
 [0 1 1 0 2 0 0]
 [0 0 8 0 1 0 0]
 [0 0 2 1 0 0 0]
 [0 0 5 0 0 0 0]
 [0 0 0 0 0 3 0]
 [0 0 2 0 0 0 0]]
Classification report:


D:\resume\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\resume\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\resume\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      0.25      0.40         4
           2       0.44      0.89      0.59         9
           3       1.00      0.33      0.50         3
           4       0.00      0.00      0.00         5
           5       1.00      1.00      1.00         3
           6       0.00      0.00      0.00         2

    accuracy                           0.59        32
   macro avg       0.63      0.50      0.50        32
weighted avg       0.62      0.59      0.54        32

Accuracy of the model:  0.59375


In [19]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression()

classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)
print(list(zip(Y_test,Y_pred)))

[2 2 2 0 3 2 3 0 2 2 1 1 2 0 2 5 2 0 1 2 0 2 2 2 0 2 2 2 3 5 2 0]
[(4, 2), (2, 2), (4, 2), (0, 0), (3, 3), (2, 2), (3, 3), (0, 0), (6, 2), (2, 2), (1, 1), (1, 1), (4, 2), (0, 0), (4, 2), (5, 5), (2, 2), (0, 0), (1, 1), (2, 2), (0, 0), (2, 2), (5, 2), (2, 2), (0, 0), (4, 2), (2, 2), (6, 2), (3, 3), (5, 5), (2, 2), (1, 0)]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report:")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test,Y_pred)
print("Accuracy of the model: ",acc)

[[6 0 0 0 0 0 0]
 [1 3 0 0 0 0 0]
 [0 0 9 0 0 0 0]
 [0 0 0 3 0 0 0]
 [0 0 5 0 0 0 0]
 [0 0 1 0 0 2 0]
 [0 0 2 0 0 0 0]]
Classification report:
              precision    recall  f1-score   support

           0       0.86      1.00      0.92         6
           1       1.00      0.75      0.86         4
           2       0.53      1.00      0.69         9
           3       1.00      1.00      1.00         3
           4       0.00      0.00      0.00         5
           5       1.00      0.67      0.80         3
           6       0.00      0.00      0.00         2

    accuracy                           0.72        32
   macro avg       0.63      0.63      0.61        32
weighted avg       0.62      0.72      0.64        32

Accuracy of the model:  0.71875


D:\resume\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\resume\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
D:\resume\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
